version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[npm]"
    open-pull-requests-limit: 10

  - package-ecosystem: "nuget"
    directory: "/src/api"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[nuget]"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
