services:
  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: on-failure:1
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "audiochan_db"
    networks:
      - audiochan
  redis:
    image: redis
  backend:
    restart: on-failure:1
    container_name: backend
    build:
      context: src/api
      dockerfile: Dockerfile
    env_file:
      - src/api/.env
    depends_on:
      - database
    networks:
      - audiochan
  frontend:
    stdin_open: true
    restart: on-failure:1
    container_name: frontend
    build:
      context: src/web
    env_file:
      - web/.env
    depends_on:
      - backend
    volumes:
      - /app/node_modules
      - /app/.next
      - /app/public
    networks:
      - audiochan

networks:
  audiochan:
    name: audiochan-net
    driver: bridge

volumes:
  postgres-db:
    name: postgres-db
