services:
  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: on-failure:1
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "tuna_db"
    networks:
      - tuna
networks:
  tuna:
    name: tuna-net
    driver: bridge

volumes:
  postgres-db:
    name: postgres-db
