name: audiochan Backend Build

on:
  push:
    branches:
      - staging
    paths:
      - "src/api/**"
  pull_request:
    paths:
      - "src/api/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies with dotnet
        run: dotnet restore ./src/api/Audiochan.sln
      - name: Build with dotnet
        run: dotnet build ./src/api/Audiochan.sln --configuration Release
      - name: Test unit tests
        run: dotnet test ./src/api/tests/Audiochan.Core.UnitTests/Audiochan.Core.UnitTests.csproj
      # - name: Test integration tests
      #   run: dotnet test ./src/api/tests/Audiochan.Core.IntegrationTests/Audiochan.Core.IntegrationTests.csproj
